# Generated by Django 5.1.7 on 2025-09-23 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking_or', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysummary',
            name='total_time',
            field=models.DurationField(default=datetime.timedelta, verbose_name='Общее время'),
        ),
    ]
