# Generated by Django 5.1.7 on 2025-09-23 10:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
from django.db.models.functions import TruncDate
from django.utils.text import slugify


def populate_counters(apps, schema_editor):
    TimeInterval = apps.get_model('time_tracking_or', 'TimeInterval')
    TimeCounter = apps.get_model('time_tracking_or', 'TimeCounter')
    app_label, model_name = settings.AUTH_USER_MODEL.split('.')
    UserModel = apps.get_model(app_label, model_name)

    TimeInterval.objects.filter(day__isnull=True, date_create__isnull=False).update(day=TruncDate('date_create'))

    users_with_intervals = (
        UserModel.objects.filter(time_intervals__isnull=False)
        .distinct()
    )

    for user in users_with_intervals:
        base_slug = slugify(f'{user.username or "user"}-counter') or f'counter-{user.pk}'
        slug = base_slug
        suffix = 1
        while TimeCounter.objects.filter(user=user, slug=slug).exists():
            slug = f'{base_slug}-{suffix}'
            suffix += 1
        counter = TimeCounter.objects.create(user=user, name='Основной счетчик', slug=slug)
        TimeInterval.objects.filter(user=user, counter__isnull=True).update(counter=counter)


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking_or', '0002_alter_dailysummary_total_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailysummary',
            options={'ordering': ('-date',), 'verbose_name': 'Суточный итог', 'verbose_name_plural': 'Суточные итоги'},
        ),
        migrations.AlterModelOptions(
            name='timeinterval',
            options={'ordering': ('-day', '-date_create'), 'verbose_name': 'Интервал', 'verbose_name_plural': 'Интервалы'},
        ),
        migrations.AddField(
            model_name='timeinterval',
            name='day',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='timeinterval',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_intervals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='dailysummary',
            unique_together={('user', 'date')},
        ),
        migrations.CreateModel(
            name='TimeCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='URL')),
                ('color', models.CharField(default='#4e79a7', max_length=7, verbose_name='Цвет')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_counters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Счетчик',
                'verbose_name_plural': 'Счетчики',
                'ordering': ('name',),
                'unique_together': {('user', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='timeinterval',
            name='counter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='time_tracking_or.timecounter'),
        ),
        migrations.RunPython(populate_counters, migrations.RunPython.noop),
    ]
