# Generated by Django 5.1.6 on 2025-02-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeinterval',
            name='duration',
            field=models.TimeField(blank=True, null=True, verbose_name='Длительность'),
        ),
    ]
