# Generated by Django 5.1.6 on 2025-02-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking_main', '0003_alter_timeinterval_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeinterval',
            name='end_time',
            field=models.DurationField(blank=True, null=True, verbose_name='стоп'),
        ),
        migrations.AlterField(
            model_name='timeinterval',
            name='start_time',
            field=models.DurationField(blank=True, null=True, verbose_name='старт'),
        ),
    ]
