# Generated by Django 5.1.6 on 2025-02-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking_main', '0004_alter_timeinterval_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeinterval',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='стоп'),
        ),
        migrations.AlterField(
            model_name='timeinterval',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='старт'),
        ),
    ]
