name: Django Migrations and Requirements Update

on:
  push:
    branches:
      - main  
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure this file is in the root

      - name: Make migrations
        run: |
          python manage.py makemigrations
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}  

      - name: Run migrations
        run: |
          python manage.py migrate
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }} 

      - name: Update requirements.txt
        run: |
          pip freeze > requirements.txt
